In [8]:
!pip install pandas ipywidgets textblob

In [1]:
import pandas as pd

df = pd.read_excel("behaviour_simulation_train.xlsx", parse_dates = ['date']) 

df['content'] = df['content'].astype(str).str.strip()
df['username'] = df['username'].astype(str).str.strip()
df['media'] = df['media'].astype(str).str.strip()

df['hour'] = df['date'].dt.hour
df['day_of_week'] = df['date'].dt.day_name()
df['month'] = df['date'].dt.month
df['year'] = df['date'].dt.year

media_dict = {'P':'Photo', 'V':'Video', 'G':'Gif'}
df['media_type'] = df['media'].str[1].map(media_dict)

df['word_count'] = df['content'].str.split().str.len()
df['char_count'] = df['content'].str.len()

In [ ]:
from textblob import TextBlob
i = 1
def get_sentiment_scores(text):
    analysis = TextBlob(text)
    global i
    print(f"Analyzing sentiment for text: {i}")
    i+=1
    return analysis.sentiment.polarity, analysis.sentiment.subjectivity

df[['sentiment_polarity', 'sentiment_subjectivity']] = df['content'].apply(lambda x: pd.Series(get_sentiment_scores(x)))

Analyzing sentiment for text: 1
Analyzing sentiment for text: 2
Analyzing sentiment for text: 3
Analyzing sentiment for text: 4
Analyzing sentiment for text: 5
Analyzing sentiment for text: 6
Analyzing sentiment for text: 7
Analyzing sentiment for text: 8
Analyzing sentiment for text: 9
Analyzing sentiment for text: 10
Analyzing sentiment for text: 11
Analyzing sentiment for text: 12
Analyzing sentiment for text: 13
Analyzing sentiment for text: 14
Analyzing sentiment for text: 15
Analyzing sentiment for text: 16
Analyzing sentiment for text: 17
Analyzing sentiment for text: 18
Analyzing sentiment for text: 19
Analyzing sentiment for text: 20
Analyzing sentiment for text: 21
Analyzing sentiment for text: 22
Analyzing sentiment for text: 23
Analyzing sentiment for text: 24
Analyzing sentiment for text: 25
Analyzing sentiment for text: 26
Analyzing sentiment for text: 27
Analyzing sentiment for text: 28
Analyzing sentiment for text: 29
Analyzing sentiment for text: 30
Analyzing sentiment

Traceback (most recent call last):
  File "c:\Users\swaya\python\.venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3672, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\swaya\AppData\Local\Temp\ipykernel_26872\2545938786.py", line 10, in <module>
    df[['sentiment_polarity', 'sentiment_subjectivity']] = df['content'].apply(lambda x: pd.Series(get_sentiment_scores(x)))
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\swaya\python\.venv\Lib\site-packages\pandas\core\series.py", line 4924, in apply
    ).apply()
      ^^^^^^^
  File "c:\Users\swaya\python\.venv\Lib\site-packages\pandas\core\apply.py", line 1427, in apply
    return self.apply_standard()
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\swaya\python\.venv\Lib\site-packages\pandas\core\apply.py", line 1507, in apply_standard
    mapped = obj._map_values(
             ^^^^^^^^^^^^^^^^

In [6]:
from textblob import TextBlob
from tqdm.notebook import tqdm

def analyze_sentiments(texts):
    polarities = []
    subjectivities = []
    
    # Use tqdm for progress tracking
    for text in tqdm(texts, desc="Analyzing texts"):
        analysis = TextBlob(text)
        polarities.append(analysis.sentiment.polarity)
        subjectivities.append(analysis.sentiment.subjectivity)
    
    return polarities, subjectivities

# Process all texts at once
df['sentiment_polarity'], df['sentiment_subjectivity'] = analyze_sentiments(df['content'])

Analyzing texts:   0%|          | 0/300000 [00:00<?, ?it/s]

In [9]:
df.info()
display(df.isnull().sum())
display(df.iloc[0:10])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 16 columns):
 #   Column                  Non-Null Count   Dtype         
---  ------                  --------------   -----         
 0   id                      300000 non-null  int64         
 1   date                    300000 non-null  datetime64[ns]
 2   likes                   300000 non-null  int64         
 3   content                 300000 non-null  object        
 4   username                300000 non-null  object        
 5   media                   300000 non-null  object        
 6   inferred company        300000 non-null  object        
 7   hour                    300000 non-null  int32         
 8   day_of_week             300000 non-null  object        
 9   month                   300000 non-null  int32         
 10  year                    300000 non-null  int32         
 11  media_type              300000 non-null  object        
 12  word_count              300000

id                        0
date                      0
likes                     0
content                   0
username                  0
media                     0
inferred company          0
hour                      0
day_of_week               0
month                     0
year                      0
media_type                0
word_count                0
char_count                0
sentiment_polarity        0
sentiment_subjectivity    0
dtype: int64

id                date  likes  \
0   1 2020-12-12 00:47:00      1   
1   2 2018-06-30 10:04:20   2750   
2   3 2020-09-29 19:47:28     57   
3   4 2020-10-01 11:40:09    152   
4   5 2018-10-19 14:30:46     41   
5   6 2020-11-15 16:01:08    525   
6   7 2019-10-24 10:51:03      0   
7   8 2018-07-17 22:04:26      3   
8   9 2019-03-27 12:18:01    572   
9  10 2020-08-01 05:24:03    127   

                                             content        username  \
0  Spend your weekend morning with a Ham, Egg, an...    TimHortonsPH   
1  Watch rapper <mention> freestyle for over an H...       IndyMusic   
2  Canadian Armenian community demands ban on mil...       CBCCanada   
3  1st in Europe to be devastated by COVID-19, It...  MKWilliamsRome   
4  Congratulations to Pauletha Butts of <mention>...           BGISD   
5  An 85-year-old primary school in Shanghai has ...            cnni   
6  LASU Celebrates New Dawn Of Unbroken Peace As ...  IndependentNGR   
7  Next week CNCF will be publishing a series of ...      CiscoCloud   
8  A 95-year-old World War II veteran says he was...            cnni   
9  Nicholas Hoult, Charlize Theron, and Aisha Tyl...        GettyVIP   

                                               media inferred company  hour  \
0  [Photo(previewUrl='https://pbs.twimg.com/media...      tim hortons     0   
1  [Photo(previewUrl='https://pbs.twimg.com/media...      independent    10   
2  [Photo(previewUrl='https://pbs.twimg.com/media...              cbc    19   
3  [Photo(previewUrl='https://pbs.twimg.com/media...         williams    11   
4  [Photo(previewUrl='https://pbs.twimg.com/media...      independent    14   
5  [Video(thumbnailUrl='https://pbs.twimg.com/amp...              cnn    16   
6  [Photo(previewUrl='https://pbs.twimg.com/media...      independent    10   
7  [Video(thumbnailUrl='https://pbs.twimg.com/amp...            cisco    22   
8  [Photo(previewUrl='https://pbs.twimg.com/media...              cnn    12   
9  [Photo(previewUrl='https://pbs.twimg.com/media...     getty images     5   

  day_of_week  month  year media_type  word_count  char_count  \
0    Saturday     12  2020      Photo          29         181   
1    Saturday      6  2018      Photo          10          73   
2     Tuesday      9  2020      Photo          14         104   
3    Thursday     10  2020      Photo          22         140   
4      Friday     10  2018      Photo          26         199   
5      Sunday     11  2020      Video          28         181   
6    Thursday     10  2019      Photo          16         107   
7     Tuesday      7  2018      Video          35         241   
8   Wednesday      3  2019      Photo          36         224   
9    Saturday      8  2020      Photo          42         274   

   sentiment_polarity  sentiment_subjectivity  
0            0.175000                0.325000  
1            0.000000                0.000000  
2           -0.100000                0.100000  
3            0.500000                0.900000  
4            0.062500                0.083333  
5            0.268182                0.477273  
6            0.136364                0.454545  
7            0.266667                0.500000  
8           -0.287879                0.484848  
9           -0.062500                0.750000

In [10]:
'''
inferred company_encoded
hour_encoded
media_type_encoded
char_count
sentiment_polarity
sentiment_subjectivity
'''

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
import joblib
import numpy as np

from sklearn.preprocessing import OneHotEncoder


X = df
y = df['likes']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
encoder.fit(df[['inferred company', 'hour', 'media_type', 'day_of_week']])

X_train_encoded = encoder.transform(X_train[['inferred company', 'hour', 'media_type']])
print(X_train_encoded)
print(X_train_encoded.shape)

X_train_encoded = np.hstack([X_train['char_count'].values.reshape(-1,1) , 
                        X_train['sentiment_polarity'].values.reshape(-1,1), 
                        X_train['sentiment_subjectivity'].values.reshape(-1,1), 
                        X_train_encoded])

print(X_train_encoded)
print(X_train_encoded.shape)


X_test_encoded = encoder.transform(X_test[['inferred company', 'hour', 'media_type']])
X_test_encoded = np.hstack([X_test['char_count'].values.reshape(-1,1),
                        X_test['sentiment_polarity'].values.reshape(-1,1), 
                        X_test['sentiment_subjectivity'].values.reshape(-1,1), 
                        X_test_encoded])

print(X_test_encoded)
print(X_test_encoded.shape)


model = RandomForestRegressor(
    warm_start=True,  # Allows adding trees incrementally
    n_estimators=0,   # Start with 0 trees
    random_state=42
)
rmse = 4931
n_epochs = 100  # Total number of trees
for i in range(1, n_epochs + 1):
    model.n_estimators = i
    model.fit(X_train_encoded, y_train)
    print(f"Fitted {i}/{n_epochs} trees")
    preds = model.predict(X_test_encoded)
    prev_rmse = rmse
    rmse = np.sqrt(mean_squared_error(y_test, preds))
    print("RMSE:", rmse, "difference:", rmse - prev_rmse)

preds = model.predict(X_test_encoded)
rmse = np.sqrt(mean_squared_error(y_test, preds))
print("RMSE:", rmse)

import joblib
joblib.dump(model, 'like_predictor.pkl')

[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(240000, 254)
[[7.20000000e+01 2.00000000e-01 1.00000000e-01 ... 1.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [1.38000000e+02 4.16666667e-01 7.12500000e-01 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [6.30000000e+01 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 ...
 [1.91000000e+02 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  1.00000000e+00 0.00000000e+00]
 [1.29000000e+02 6.90476190e-02 6.57142857e-01 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [1.56000000e+02 4.00000000e-01 3.75000000e-01 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]]
(240000, 257)
[[ 9.50000000e+01  4.75000000e-01  5.50000000e-01 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 1.19000000e+02  4.75000000e-01  7.75000000e-01 ...  0.00000000e+00
   1.00000000e+00  0.00000000e+00]
 [ 8.5

KeyboardInterrupt: 

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
import joblib
import numpy as np
from sklearn.preprocessing import OneHotEncoder

y = df['likes']

X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.2, random_state=42)

# using log(likes) as target variable
y_train = np.log1p(y_train)

encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
encoder.fit(df[['media_type', 'hour']])

X_train_final = encoder.transform(X_train[['media_type', 'hour']])

X_test_final = encoder.transform(X_test[['media_type', 'hour']])


username_avg_likes_train = X_train.groupby('username')['likes'].transform('mean').values.reshape(-1,1)
company_avg_likes_train = X_train.groupby('inferred company')['likes'].transform('mean').values.reshape(-1,1)

# username_avg_likes for x_test will be the username_avg_likes from the training set if username is in training set\
# else it will be 0 

username_avg_likes_test = X_test['username'].map(X_train.groupby('username')['likes'].mean()).fillna(0).values.reshape(-1,1)
company_avg_likes_test = X_test['inferred company'].map(X_train.groupby('inferred company')['likes'].mean()).fillna(0).values.reshape(-1,1)


X_train_final = np.hstack([
    X_train['char_count'].values.reshape(-1,1),
    X_train['word_count'].values.reshape(-1,1), 
    X_train['sentiment_polarity'].values.reshape(-1,1), 
    X_train['sentiment_subjectivity'].values.reshape(-1,1),
    X_train_final,  # encoded media_type
    username_avg_likes_train,
    company_avg_likes_train
])

X_test_final = np.hstack([
    X_test['char_count'].values.reshape(-1,1),
    X_test['word_count'].values.reshape(-1,1),
    X_test['sentiment_polarity'].values.reshape(-1,1), 
    X_test['sentiment_subjectivity'].values.reshape(-1,1),
    X_test_final,  # encoded media_type
    username_avg_likes_test,
    company_avg_likes_test
])

model = RandomForestRegressor(random_state=21)
model.fit(X_train_final, y_train)
preds = model.predict(X_test_final)
from sklearn.metrics import mean_squared_error

preds = np.expm1(preds)
rmse = np.sqrt(mean_squared_error(y_test, preds))
print("RMSE:", rmse)


RMSE: 4391.109625032822


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
import joblib
import numpy as np
from sklearn.preprocessing import OneHotEncoder

y = df_merged['likes']

X_train, X_test, y_train, y_test = train_test_split(df_merged, y, test_size=0.2, random_state=42)

# using log(likes) as target variable
y_train = np.log1p(y_train)

encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
encoder.fit(df[['media_type', 'hour']])

X_train_final = encoder.transform(X_train[['media_type', 'hour']])

X_test_final = encoder.transform(X_test[['media_type', 'hour']])

# THERE ARE TWO STRATEGIES: MEAN STRATEGY AND 0 STRATEGY

username_avg_likes_train = X_train.groupby('username')['likes'].transform('mean').values.reshape(-1,1)
company_avg_likes_train = X_train.groupby('inferred company')['likes'].transform('mean').values.reshape(-1,1)

# username_avg_likes for x_test will be the username_avg_likes from the training set if username is in training set\
# else it will be 0 

username_avg_likes_test = X_test['username'].map(X_train.groupby('username')['likes'].mean()).fillna(0).values.reshape(-1,1)
company_avg_likes_test = X_test['inferred company'].map(X_train.groupby('inferred company')['likes'].mean()).fillna(0).values.reshape(-1,1)

# no media_type, polarity, subjectivity, word_count, username_avg, company_avg
X_train_final = np.hstack([
    X_train['char_count'].values.reshape(-1,1),
    X_train['followers'].values.reshape(-1,1),
    X_train['following'].values.reshape(-1,1),
    X_train['statusesCount'].values.reshape(-1,1),
    X_train['favouritesCount'].values.reshape(-1,1),
    X_train['mediaCount'].values.reshape(-1,1)
])

X_test_final = np.hstack([
    X_test['char_count'].values.reshape(-1,1),
    X_test['followers'].values.reshape(-1,1),
    X_test['following'].values.reshape(-1,1),
    X_test['statusesCount'].values.reshape(-1,1),
    X_test['favouritesCount'].values.reshape(-1,1),
    X_test['mediaCount'].values.reshape(-1,1)
])

model = RandomForestRegressor(random_state=21)
model.fit(X_train_final, y_train)
preds = model.predict(X_test_final)
from sklearn.metrics import mean_squared_error

preds = np.expm1(preds)
rmse = np.sqrt(mean_squared_error(y_test, preds))
print("RMSE:", rmse)


RMSE: 4565.388493826037


In [153]:
username_avg_likes = df_merged.groupby('username')['likes'].transform('mean')
company_avg_likes = df_merged.groupby('inferred company')['likes'].transform('mean')

In [154]:
display(username_avg_likes)
display(company_avg_likes)

0            3.670270
1          441.894737
2           95.671698
3          256.151515
4           63.403226
             ...     
299995       0.269825
299996     268.197937
299997     417.506711
299998     325.888799
299999    1309.835913
Name: likes, Length: 300000, dtype: float64

0          160.179678
1           49.258918
2          204.387701
3         2093.835052
4           49.258918
             ...     
299995      49.258918
299996     204.387701
299997    2093.835052
299998      49.258918
299999    1791.161267
Name: likes, Length: 300000, dtype: float64

In [156]:
likes_to_follower_ratio = username_avg_likes/df_merged['followers']
display(likes_to_follower_ratio)

0         0.001798
1         0.014240
2         0.000390
3         0.039683
4         0.008115
            ...   
299995    0.000004
299996    0.001082
299997    0.004398
299998    0.000093
299999    0.000087
Length: 300000, dtype: float64

In [162]:
1/likes_to_follower_ratio.mean()

np.float64(5.703983747299888)

In [163]:
print(username_avg_likes.iloc[0:10]/0.17531606755951454, df_merged['followers'])

0      20.935162
1    2520.560397
2     545.709811
3    1461.084079
4     361.650970
5    7471.282761
6       1.539078
7      14.158555
8    7471.282761
9    7226.249308
Name: likes, dtype: float64 0             2041.0
1            31033.0
2           245542.0
3             6455.0
4             7813.0
             ...    
299995       72840.0
299996      247825.0
299997       94936.0
299998     3511956.0
299999    15076156.0
Name: followers, Length: 300000, dtype: float64


In [146]:
data = pd.read_csv("usernames_data_x.csv", parse_dates=['createdAt'])
data.info()
display(data.isnull().sum())
display(data.head())


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2249 entries, 0 to 2248
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype              
---  ------           --------------  -----              
 0   userName         2249 non-null   object             
 1   id               2249 non-null   float64            
 2   name             2249 non-null   object             
 3   followers        2249 non-null   int64              
 4   following        2249 non-null   int64              
 5   isBlueVerified   2249 non-null   bool               
 6   verifiedType     604 non-null    object             
 7   statusesCount    2249 non-null   int64              
 8   mediaCount       2249 non-null   int64              
 9   favouritesCount  2249 non-null   int64              
 10  createdAt        2249 non-null   datetime64[ns, UTC]
 11  location         1788 non-null   object             
 12  description      2184 non-null   object             
 13  canDm            2

userName              0
id                    0
name                  0
followers             0
following             0
isBlueVerified        0
verifiedType       1645
statusesCount         0
mediaCount            0
favouritesCount       0
createdAt             0
location            461
description          65
canDm                 0
dtype: int64

userName            id                               name  followers  \
0    TimHortonsPH  7.944183e+17            Tim Hortons Philippines       2041   
1       IndyMusic  1.730888e+07                  Independent Music      31033   
2       CBCCanada  1.896579e+07                  CBC Canadian News     245542   
3  MKWilliamsRome  7.549140e+08                     Megan Williams       6455   
4           BGISD  2.206200e+07  Bowling Green Independent Schools       7813   

   following  isBlueVerified verifiedType  statusesCount  mediaCount  \
0          9           False          NaN            931         687   
1        557           False          NaN          31733        4853   
2          5           False          NaN          93717       53557   
3       1007           False          NaN           5739        1294   
4        193            True          NaN           7397        2347   

   favouritesCount                 createdAt                     location  \
0              954 2016-11-04 05:57:45+00:00  Republic of the Philippines   
1              104 2008-11-11 12:43:57+00:00                       London   
2               11 2009-01-14 03:42:38+00:00                       Canada   
3            10180 2012-08-13 10:53:48+00:00                          NaN   
4             5311 2009-02-26 21:06:29+00:00      Bowling Green, Kentucky   

                                         description  canDm  
0  Welcome to the official account of Tim Hortons...  False  
1  Music news, reviews, and feature stories from ...  False  
2  Canadian news and features, and the Politics B...  False  
3  Report on radio & TV & write on Italy, Europe ...  False  
4  Every day, accomplishments of students and emp...  False

In [125]:
# no. of different verified types

import matplotlib.pyplot as plt
# count of verified types, isBlueVerified, isAutomated, hasCustomTimelines, isTranslator, canDm, withheldInCountries, possiblySensitive,  affiliatesHighlightedLabel, pinnedTweetIds
display(data['verifiedType'].value_counts(dropna=False))
display(data['isBlueVerified'].value_counts(dropna=False))
display(data['isAutomated'].value_counts(dropna=False))
display(data['hasCustomTimelines'].value_counts(dropna=False))
display(data['isTranslator'].value_counts(dropna=False))
display(data['canDm'].value_counts(dropna=False))
display(data['withheldInCountries'].value_counts(dropna=False))
display(data['possiblySensitive'].value_counts(dropna=False))
display(data['affiliatesHighlightedLabel'].value_counts(dropna=False))
display(data['pinnedTweetIds'].value_counts(dropna=False))


verifiedType
NaN           1645
Business       566
Government      38
Name: count, dtype: int64

isBlueVerified
False    1705
True      544
Name: count, dtype: int64

isAutomated
False    2249
Name: count, dtype: int64

hasCustomTimelines
False    2249
Name: count, dtype: int64

isTranslator
False    2249
Name: count, dtype: int64

canDm
False    1246
True     1003
Name: count, dtype: int64

withheldInCountries
[]    2249
Name: count, dtype: int64

possiblySensitive
False    2249
Name: count, dtype: int64

affiliatesHighlightedLabel
{}    2249
Name: count, dtype: int64

pinnedTweetIds
[]    2249
Name: count, dtype: int64

In [144]:
# dropping isAutomated, hasCustomTimelines, isTranslator, withheldInCountries, possiblySensitive, affiliatesHighlightedLabel, pinnedTweetIds, profile_bio_description since they are all none/empty
data = data.drop(columns=['isAutomated', 'hasCustomTimelines', 'isTranslator', 'withheldInCountries', 'possiblySensitive', 'affiliatesHighlightedLabel', 'pinnedTweetIds', 'profile_bio_description'])
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2249 entries, 0 to 2248
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype              
---  ------           --------------  -----              
 0   userName         2249 non-null   object             
 1   id               2249 non-null   float64            
 2   name             2249 non-null   object             
 3   followers        2249 non-null   int64              
 4   following        2249 non-null   int64              
 5   isBlueVerified   2249 non-null   bool               
 6   verifiedType     604 non-null    object             
 7   statusesCount    2249 non-null   int64              
 8   mediaCount       2249 non-null   int64              
 9   favouritesCount  2249 non-null   int64              
 10  createdAt        2249 non-null   datetime64[ns, UTC]
 11  location         1788 non-null   object             
 12  description      2184 non-null   object             
 13  canDm            2

In [145]:
data.to_csv("usernames_data_x.csv", index=False)

In [128]:
data = data.drop(columns=['profile_bio_description'])

In [98]:
# Read just the first column of line 517
import pandas as pd

line_517 = pd.read_csv("usernames_data_x.csv", 
                       skiprows=range(1, 515),  # Skip to line 517
                       nrows=1,        )            # Read only first column

print(f"Line 517, first column: {line_517.iloc[0]}")

Line 517, first column: userName                                              revlon
id                                                 130522705
name                                                  Revlon
followers                                             437584
following                                                485
isBlueVerified                                         False
verifiedType                                             NaN
statusesCount                                          19519
mediaCount                                              6005
favouritesCount                                        12211
createdAt                        2010-04-07T14:49:42.000000Z
location                                                 NaN
description                   Hold Nothing Back. #LIVEBOLDLY
profile_bio_description                                  NaN
isAutomated                                            False
hasCustomTimelines                                     False


In [150]:
df_merged = pd.merge(df, data, left_on='username', right_on='userName', how='left')
print(df_merged.shape)
print(df_merged.info())
display(df_merged.isnull().sum())
print(df_merged.head())


(300000, 30)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 30 columns):
 #   Column                  Non-Null Count   Dtype              
---  ------                  --------------   -----              
 0   id_x                    300000 non-null  int64              
 1   date                    300000 non-null  datetime64[ns]     
 2   likes                   300000 non-null  int64              
 3   content                 300000 non-null  object             
 4   username                300000 non-null  object             
 5   media                   300000 non-null  object             
 6   inferred company        300000 non-null  object             
 7   hour                    300000 non-null  int32              
 8   day_of_week             300000 non-null  object             
 9   month                   300000 non-null  int32              
 10  year                    300000 non-null  int32              
 11  media_type   

id_x                           0
date                           0
likes                          0
content                        0
username                       0
media                          0
inferred company               0
hour                           0
day_of_week                    0
month                          0
year                           0
media_type                     0
word_count                     0
char_count                     0
sentiment_polarity             0
sentiment_subjectivity         0
userName                   11656
id_y                       11656
name                       11656
followers                  11656
following                  11656
isBlueVerified             11656
verifiedType              178564
statusesCount              11656
mediaCount                 11656
favouritesCount            11656
createdAt                  11656
location                   68585
description                15284
canDm                      11656
dtype: int

   id_x                date  likes  \
0     1 2020-12-12 00:47:00      1   
1     2 2018-06-30 10:04:20   2750   
2     3 2020-09-29 19:47:28     57   
3     4 2020-10-01 11:40:09    152   
4     5 2018-10-19 14:30:46     41   

                                             content        username  \
0  Spend your weekend morning with a Ham, Egg, an...    TimHortonsPH   
1  Watch rapper <mention> freestyle for over an H...       IndyMusic   
2  Canadian Armenian community demands ban on mil...       CBCCanada   
3  1st in Europe to be devastated by COVID-19, It...  MKWilliamsRome   
4  Congratulations to Pauletha Butts of <mention>...           BGISD   

                                               media inferred company  hour  \
0  [Photo(previewUrl='https://pbs.twimg.com/media...      tim hortons     0   
1  [Photo(previewUrl='https://pbs.twimg.com/media...      independent    10   
2  [Photo(previewUrl='https://pbs.twimg.com/media...              cbc    19   
3  [Photo(previewUrl='

In [165]:
display(df_merged.isnull().sum())

id_x                           0
date                           0
likes                          0
content                        0
username                       0
media                          0
inferred company               0
hour                           0
day_of_week                    0
month                          0
year                           0
media_type                     0
word_count                     0
char_count                     0
sentiment_polarity             0
sentiment_subjectivity         0
userName                   11656
id_y                       11656
name                       11656
followers                  11656
following                  11656
isBlueVerified             11656
verifiedType              178564
statusesCount              11656
mediaCount                 11656
favouritesCount            11656
createdAt                  11656
location                   68585
description                15284
canDm                      11656
dtype: int

In [149]:
df_merged.to_csv('300,000_tweets.csv', index=False)

In [120]:
import os
size_bytes = os.path.getsize('behaviour_simulation_train.xlsx')
print(f"Size of '300,000_tweets.csv': {size_bytes / (1024 * 1024)} MB")

Size of '300,000_tweets.csv': 54.112149238586426 MB


In [121]:
df = pd.read_csv('300,000_tweets.csv', parse_dates=['date', 'createdAt'])
print(df.isnull().sum())

id_x                               0
date                               0
likes                              0
content                            0
username                           0
media                              0
inferred company                   0
hour                               0
day_of_week                        0
month                              0
year                               0
media_type                         0
word_count                         0
char_count                         0
sentiment_polarity                 0
sentiment_subjectivity             0
userName                       11656
id_y                           11656
name                           11656
followers                      11656
following                      11656
isBlueVerified                 11656
verifiedType                  178564
statusesCount                  11656
mediaCount                     11656
favouritesCount                11656
createdAt                      11656
l

In [54]:
!pip install sentence-transformers
!pip install transformers
!pip install tf-keras


   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ------------ --------------------------- 0.5/1.7 MB 3.3 MB/s eta 0:00:01
   ------------------------------ --------- 1.3/1.7 MB 3.5 MB/s eta 0:00:01
   ---------------------------------------- 1.7/1.7 MB 3.6 MB/s eta 0:00:00


In [55]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('all-MiniLM-L6-v2')

embeddings = model.encode(df['content'].tolist(), show_progress_bar=True, convert_to_numpy=True)
print(embeddings.shape)
print(embeddings)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

c:\Users\swaya\python\.venv\Lib\site-packages\huggingface_hub\file_download.py:144: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\swaya\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/9375 [00:00<?, ?it/s]

(300000, 384)
[[-0.03698691 -0.0214316   0.11477823 ... -0.00515601 -0.00155299
  -0.08958418]
 [-0.05627382 -0.08745369  0.0368     ...  0.06174331 -0.00369593
  -0.05814916]
 [ 0.00012053  0.03061481 -0.02489772 ... -0.01552051  0.04840955
  -0.00649815]
 ...
 [-0.0311013  -0.01838605  0.01456273 ...  0.05102251 -0.05376613
   0.05286839]
 [-0.02998556 -0.00998588  0.00249656 ... -0.07167885 -0.09088012
   0.1055689 ]
 [ 0.03460238 -0.01274594 -0.05576073 ... -0.00344945  0.00224052
   0.00631149]]


In [78]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('all-MiniLM-L6-v2')

x = model.encode("Spend your weekend morning with a Ham, Egg, and Cheese Wrap paired with a sweet Iced French Vanilla! ☀️ Order yours now via dine-in, takeout, and delivery. #TimHortonsPH <hyperlink>")
print(x)

[-3.69868912e-02 -2.14316100e-02  1.14778236e-01  2.42233593e-02
  3.07437358e-03  3.20138633e-02  5.66247031e-02 -1.28610816e-03
 -1.78292282e-02 -5.75575884e-03  2.08586664e-03 -9.65242554e-03
 -6.21038117e-02 -6.00784756e-02 -7.65424781e-03 -8.16671774e-02
  2.84370035e-02 -4.47237864e-02  2.17984635e-02  5.95903164e-03
  3.35813337e-03 -6.91249445e-02  6.72821999e-02  5.07890955e-02
 -3.91572006e-02  5.04854359e-02  8.47654417e-03 -2.01261472e-02
 -8.57564434e-03 -8.64346921e-02 -5.29940985e-02  3.34236771e-02
 -3.18259448e-02 -1.87266916e-02 -2.68637221e-02  2.59937216e-02
  9.92912129e-02 -4.63465825e-02  4.31814827e-02  1.53249530e-02
  1.25390822e-02 -1.34181734e-02 -4.30429503e-02  3.69362719e-02
 -2.62608714e-02  1.03990976e-02 -1.50249377e-02  3.95765863e-02
 -1.26049044e-02  9.58121866e-02 -1.95345432e-02  1.05271265e-02
  2.19309684e-02  1.50648393e-02  2.11420245e-02  5.68872951e-02
 -9.13483053e-02 -9.05354768e-02  4.55621816e-02  1.05560176e-01
 -4.40262184e-02  4.88548

In [57]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
import joblib
import numpy as np
from sklearn.preprocessing import OneHotEncoder

# using all-MiniLM-L6-v2 embeddings model for embedding content
# adding embeddings to the dataframe

# using neural network as model to train


y = df['likes']

X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.2, random_state=42)
embeddings_train, embeddings_test = train_test_split(embeddings, test_size=0.2, random_state=42)

# using log(likes) as target variable
y_train = np.log1p(y_train)

encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
encoder.fit(df[['media_type', 'hour']])

X_train_final = encoder.transform(X_train[['media_type', 'hour']])

X_test_final = encoder.transform(X_test[['media_type', 'hour']])


username_avg_likes_train = X_train.groupby('username')['likes'].transform('mean').values.reshape(-1,1)
company_avg_likes_train = X_train.groupby('inferred company')['likes'].transform('mean').values.reshape(-1,1)

# username_avg_likes for x_test will be the username_avg_likes from the training set if username is in training set\
# else it will be 0 

username_avg_likes_test = X_test['username'].map(X_train.groupby('username')['likes'].mean()).fillna(0).values.reshape(-1,1)
company_avg_likes_test = X_test['inferred company'].map(X_train.groupby('inferred company')['likes'].mean()).fillna(0).values.reshape(-1,1)


X_train_final = np.hstack([
    X_train['char_count'].values.reshape(-1,1),
    X_train['word_count'].values.reshape(-1,1), 
    X_train['sentiment_polarity'].values.reshape(-1,1), 
    X_train['sentiment_subjectivity'].values.reshape(-1,1),
    X_train_final,  # encoded media_type
    username_avg_likes_train,
    company_avg_likes_train,
    embeddings_train  # embeddings for content
])

X_test_final = np.hstack([
    X_test['char_count'].values.reshape(-1,1),
    X_test['word_count'].values.reshape(-1,1),
    X_test['sentiment_polarity'].values.reshape(-1,1), 
    X_test['sentiment_subjectivity'].values.reshape(-1,1),
    X_test_final,  # encoded media_type
    username_avg_likes_test,
    company_avg_likes_test,
    embeddings_test  # embeddings for content
])


model = RandomForestRegressor()
model.fit(X_train_final, y_train)
preds = model.predict(X_test_final)
from sklearn.metrics import mean_squared_error

preds = np.expm1(preds)
rmse = np.sqrt(mean_squared_error(y_test, preds))
print("RMSE:", rmse)


RMSE: 4313.44887565647


In [ ]:
from sklearn.model_selection import train_test_split

from sklearn.metrics import mean_squared_error
import joblib
import numpy as np
from sklearn.preprocessing import OneHotEncoder

# using all-MiniLM-L6-v2 embeddings model for embedding content
# adding embeddings to the dataframe

# using neural network as model to train


y = df['likes']

X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.2, random_state=42)
embeddings_train, embeddings_test = train_test_split(embeddings, test_size=0.2, random_state=42)

# using log(likes) as target variable
y_train = np.log1p(y_train)

encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
encoder.fit(df[['media_type', 'hour']])

X_train_final = encoder.transform(X_train[['media_type', 'hour']])

X_test_final = encoder.transform(X_test[['media_type', 'hour']])


username_avg_likes_train = X_train.groupby('username')['likes'].transform('mean').values.reshape(-1,1)
company_avg_likes_train = X_train.groupby('inferred company')['likes'].transform('mean').values.reshape(-1,1)

# username_avg_likes for x_test will be the username_avg_likes from the training set if username is in training set\
# else it will be 0 

username_avg_likes_test = X_test['username'].map(X_train.groupby('username')['likes'].mean()).fillna(0).values.reshape(-1,1)
company_avg_likes_test = X_test['inferred company'].map(X_train.groupby('inferred company')['likes'].mean()).fillna(0).values.reshape(-1,1)


X_train_final = np.hstack([
    X_train['char_count'].values.reshape(-1,1),
    X_train['word_count'].values.reshape(-1,1), 
    X_train['sentiment_polarity'].values.reshape(-1,1), 
    X_train['sentiment_subjectivity'].values.reshape(-1,1),
    X_train_final,  # encoded media_type
    username_avg_likes_train,
    company_avg_likes_train,
    embeddings_train  # embeddings for content
])

X_test_final = np.hstack([
    X_test['char_count'].values.reshape(-1,1),
    X_test['word_count'].values.reshape(-1,1),
    X_test['sentiment_polarity'].values.reshape(-1,1), 
    X_test['sentiment_subjectivity'].values.reshape(-1,1),
    X_test_final,  # encoded media_type
    username_avg_likes_test,
    company_avg_likes_test,
    embeddings_test  # embeddings for content
])

In [70]:
from sklearn.model_selection import train_test_split

from sklearn.metrics import mean_squared_error
import joblib
import numpy as np
from sklearn.preprocessing import OneHotEncoder

# using all-MiniLM-L6-v2 embeddings model for embedding content
# adding embeddings to the dataframe

# using neural network as model to train


y = df['likes']

X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.2, random_state=42)
embeddings_train, embeddings_test = train_test_split(embeddings, test_size=0.2, random_state=42)

# using log(likes) as target variable
y_train = np.log1p(y_train)

encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
encoder.fit(df[['media_type', 'hour']])

X_train_final = encoder.transform(X_train[['media_type', 'hour']])

X_test_final = encoder.transform(X_test[['media_type', 'hour']])


username_avg_likes_train = X_train.groupby('username')['likes'].transform('mean').values.reshape(-1,1)
company_avg_likes_train = X_train.groupby('inferred company')['likes'].transform('mean').values.reshape(-1,1)

# username_avg_likes for x_test will be the username_avg_likes from the training set if username is in training set\
# else it will be 0 

username_avg_likes_test = X_test['username'].map(X_train.groupby('username')['likes'].mean()).fillna(0).values.reshape(-1,1)
company_avg_likes_test = X_test['inferred company'].map(X_train.groupby('inferred company')['likes'].mean()).fillna(0).values.reshape(-1,1)


X_train_final = np.hstack([
    embeddings_train  # embeddings for content
])
print(X_test_final.shape)

X_test_final = np.hstack([
    embeddings_test  # embeddings for content
])





(60000, 27)


In [71]:
print(X_train_final.shape)
print(X_test_final.shape)
print(X_train_final[:5])
print(X_test_final[:5])
print(y_train[:5])
print(y_test[:5])
print(embeddings_train[:5])
print(embeddings_test[:5])
print(embeddings_train.shape)
print(embeddings_test.shape)

(240000, 384)
(60000, 384)
[[ 0.02655915 -0.03179161  0.11387632 ...  0.00643332  0.00670878
  -0.00710899]
 [-0.01448636  0.05946016  0.06709883 ...  0.00891042  0.06104576
  -0.03039043]
 [-0.04679446 -0.04184343 -0.0818503  ... -0.02846487 -0.05330222
   0.12220775]
 [ 0.02369005  0.01383924  0.06137302 ...  0.09462489 -0.10588565
   0.03249181]
 [ 0.0758625   0.01103968  0.02372216 ...  0.03227007 -0.0246997
   0.03082939]]
[[ 0.03433981  0.1031829   0.02198863 ...  0.11032947 -0.0667593
  -0.01601084]
 [-0.0348167   0.02825351  0.02565403 ...  0.03691849 -0.03450023
  -0.04965768]
 [-0.11093765  0.0990944   0.08843075 ... -0.06138143  0.00379332
   0.0662204 ]
 [-0.01126832  0.13020156 -0.01652681 ...  0.07525262  0.04463822
  -0.02821811]
 [ 0.02233414  0.0006483   0.00370507 ...  0.00944271 -0.01363
  -0.01083147]]
254099    6.063785
53461     5.337538
247984    0.000000
209067    3.135494
185997    3.737670
Name: likes, dtype: float64
4941       94
51775      23
115253    187
2

In [76]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Define input shape
input_shape = X_train_final.shape[1]
print("Input shape:", input_shape)

# Build the model
model = keras.Sequential([
    keras.layers.Input(shape=(input_shape,)),
    keras.layers.Dense(256, activation='relu'),
    keras.layers.Dropout(0.3),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(1)  # Regression output
])

# Compile the model
model.compile(optimizer='adam', loss='mse', metrics=[tf.keras.metrics.RootMeanSquaredError()])

# Early stopping to prevent overfitting
early_stop = keras.callbacks.EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

import numpy as np
from sklearn.metrics import mean_squared_error

class TestRMSECallback(keras.callbacks.Callback):
    def __init__(self, X_test, y_test):
        super().__init__()
        self.X_test = X_test
        self.y_test = y_test

    def on_epoch_end(self, epoch, logs=None):
        preds = self.model.predict(self.X_test, verbose=1).flatten()
        preds = np.expm1(preds)  # Inverse log1p transform if needed
        rmse = np.sqrt(mean_squared_error(self.y_test, preds))
        print(f"Epoch {epoch + 1}: Test RMSE = {rmse:.4f}")

test_rmse_callback = TestRMSECallback(X_test_final, y_test)

history = model.fit(
    X_train_final, y_train,
    validation_split=0.2,
    epochs=30,
    batch_size=512,
    callbacks=[early_stop, test_rmse_callback],
    verbose=1
)


# Predict and inverse log transform
preds = model.predict(X_test_final).flatten()
preds = np.expm1(preds)

# Calculate RMSE
rmse = np.sqrt(mean_squared_error(y_test, preds))
print("RMSE:", rmse)

Input shape: 384
Epoch 1/30
1875/1875 [==============================] - 4s 2ms/step
Epoch 1: Test RMSE = 4846.6873
375/375 [==============================] - 9s 22ms/step - loss: 4.8398 - root_mean_squared_error: 2.1999 - val_loss: 3.5881 - val_root_mean_squared_error: 1.8942
Epoch 2/30
1875/1875 [==============================] - 4s 2ms/step
Epoch 2: Test RMSE = 4810.4515
375/375 [==============================] - 8s 21ms/step - loss: 3.4931 - root_mean_squared_error: 1.8690 - val_loss: 3.1268 - val_root_mean_squared_error: 1.7683
Epoch 3/30
1875/1875 [==============================] - 4s 2ms/step
Epoch 3: Test RMSE = 4813.5064
375/375 [==============================] - 7s 20ms/step - loss: 3.2087 - root_mean_squared_error: 1.7913 - val_loss: 2.9198 - val_root_mean_squared_error: 1.7087
Epoch 4/30
1875/1875 [==============================] - 4s 2ms/step
Epoch 4: Test RMSE = 4819.6778
375/375 [==============================] - 8s 21ms/step - loss: 2.9882 - root_mean_squared_error: 1.7

KeyboardInterrupt: 

In [ ]:
import requests

url = "https://api.twitterapi.io/twitter/user/info"

querystring = {"userName":"TimHortonsPH"}

headers = {"X-API-Key": "ad51dfd5153142c19f85486cf9dea4d6"}

response = requests.request("GET", url, headers=headers, params=querystring)

print(response.text)
if response.status == 200:
    follower_count = response.json().get('users').get('followersCount', 0)

import requests

url = "https://api.twitterapi.io/twitter/user/info"

all_usernames = pd.read_excel("behaviour_simulation_train.xlsx")['username'].unique().tolist()

querystring = {"userName":"TimHortonsPH"}

headers = {"X-API-Key": "ad51dfd5153142c19f85486cf9dea4d6"}

response = requests.request("GET", url, headers=headers, params=querystring)

print(response.text)
json = response.json()
print(json)
print(json['data']['followers'])

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
import joblib
import numpy as np

from sklearn.preprocessing import OneHotEncoder


X = df
y = df['likes']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
encoder.fit(df[['inferred company', 'hour', 'media_type', 'day_of_week']])

X_train_encoded = encoder.transform(X_train[['inferred company', 'hour', 'media_type', 'day_of_week']])
print(X_train_encoded)
print(X_train_encoded.shape)

X_train_encoded = np.hstack([X_train['char_count'].values.reshape(-1,1) , 
                        X_train['sentiment_polarity'].values.reshape(-1,1), 
                        X_train['sentiment_subjectivity'].values.reshape(-1,1), 
                        X_train_encoded])

print(X_train_encoded)
print(X_train_encoded.shape)


X_test_encoded = encoder.transform(X_test[['inferred company', 'hour', 'media_type', 'day_of_week']])
X_test_encoded = np.hstack([X_test['char_count'].values.reshape(-1,1),
                        X_test['sentiment_polarity'].values.reshape(-1,1), 
                        X_test['sentiment_subjectivity'].values.reshape(-1,1), 
                        X_test_encoded])

print(X_test_encoded)
print(X_test_encoded.shape)


model = RandomForestRegressor(
    warm_start=True,  # Allows adding trees incrementally
    n_estimators=0,   # Start with 0 trees
    random_state=42
)

n_epochs = 100  # Total number of trees
for i in range(1, n_epochs + 1):
    model.n_estimators = i
    model.fit(X_train_encoded, y_train)
    print(f"Fitted {i}/{n_epochs} trees")

preds = model.predict(X_test_encoded)
rmse = np.sqrt(mean_squared_error(y_test, preds))
print("RMSE:", rmse)

import joblib
joblib.dump(model, 'like_predictor.pkl')

In [43]:
from sklearn.metrics import mean_squared_error

import numpy as np

average = df['likes'].mean()

rmse = np.sqrt(mean_squared_error(df['likes'], average * np.ones_like(df['likes'])))
print("RMSE:", rmse)

RMSE: 4931.455200077608


In [29]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
encoder.fit(df[['username', 'media_type', 'inferred company']])

OneHotEncoder(handle_unknown='ignore', sparse_output=False)

In [34]:
df_encoded = encoder.transform(df[['username', 'media_type', 'inferred company']])
print(df_encoded)
print(df_encoded.shape)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(300000, 2672)


In [23]:
all_usernames = df['username'].unique().tolist()
print(all_usernames)

['TimHortonsPH', 'IndyMusic', 'CBCCanada', 'MKWilliamsRome', 'BGISD', 'cnni', 'IndependentNGR', 'CiscoCloud', 'GettyVIP', 'McAfee', 'MitsubishiHVAC', 'CNN', 'Pfizer_UK', 'ToyotaShowcase', 'townsendbell', 'WalmartWorld', 'cnnphilippines', 'MFG_GM', 'cnnbrk', 'GettySport', 'MayoClinic', 'NokiamobileIN', 'LisaDNews', 'Walmart', 'Nico_Lang', 'KateWilliamsme', 'MHinfo_en', 'UnitedRentals', 'WilliamsRacing', 'CBCNB', 'Toyota_Fortuner', 'ToyotaSD', 'AAAOklahoma', 'HobbyLobby', 'NH7', 'AMCtvUK', 'Aaryn_Williams', 'Independent', 'CiscoCanada', 'TourofBritain', 'AmwayUS', 'ShopRiteStores', 'redbullracing', 'EuroLeague', 'Shell', 'poornabell', 'w_terrence', 'RadioFreeAsia', 'CheetahsRugby', 'freep', 'quintonjbell', 'AMCTheatres', 'MSFTResearch', 'bing', 'CBCPolitics', 'Cameron_Gray', 'METROFMSA', 'EMR_Automation', 'ciscoapac', 'OriginalFresca', 'CBCToronto', 'bayer04_en', 'EmersonLotzia', 'Shoprite_SA', 'ToyotaFanZone', 'ChampionsCup', 'SamsungMobile', 'NoLayingUp', 'TD_Canada', 'TargetCenterMN',